// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbonAPfOyCAhnWyBqQuTe0_HsAXcesvIg',
    appId: '1:792805524778:web:37a9f2cdae6124676d0a53',
    messagingSenderId: '792805524778',
    projectId: 'nupay-b7d2a',
    authDomain: 'nupay-b7d2a.firebaseapp.com',
    storageBucket: 'nupay-b7d2a.appspot.com',
    measurementId: 'G-XNC17YDFXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACfYup6dscksuATrw9YLQE0WDPQ0AM5VI',
    appId: '1:792805524778:android:3bb0481ae1e630026d0a53',
    messagingSenderId: '792805524778',
    projectId: 'nupay-b7d2a',
    storageBucket: 'nupay-b7d2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA0mDZazmEKtR6iPf-oFDm1DbIkoRo3Oo',
    appId: '1:792805524778:ios:e2597306bf06a0776d0a53',
    messagingSenderId: '792805524778',
    projectId: 'nupay-b7d2a',
    storageBucket: 'nupay-b7d2a.appspot.com',
    iosClientId:
        '792805524778-cku1drmfnaqnhilhr7qn0mufjd5rmlqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA0mDZazmEKtR6iPf-oFDm1DbIkoRo3Oo',
    appId: '1:792805524778:ios:e2597306bf06a0776d0a53',
    messagingSenderId: '792805524778',
    projectId: 'nupay-b7d2a',
    storageBucket: 'nupay-b7d2a.appspot.com',
    iosClientId:
        '792805524778-cku1drmfnaqnhilhr7qn0mufjd5rmlqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.c',
  );
}
